
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: smartide-docs
      ports: # 申明端口
        tools-webide-vscode: 6800
        tools-ssh: 6822
        apps-hugo-docs: 1313
      ide-type: vscode
      volumes: 
        git-config: true
        ssh-key: true
      command:
        - git submodule update --init --recursive
        - cd docs
        - npm install
        - hugo server --bind 0.0.0.0 --disableFastRender --forceSyncStatic --buildDrafts --buildFuture 
    services:
      smartide-docs:
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-vscode:all-version
        restart: always
        environment:
          ROOT_PASSWORD: root123
        volumes:
          - .:/home/project
        ports:
          - 1313:1313
          - 6800:3000
          - 6822:22
        networks:
          - smartide-network

    networks:
      smartide-network:
        external: true
