# $(github_pat) is in pipeline varialbes
name: $(date:yyyyMMdd)$(rev:.r)_$(Build.BuildId)_$(SourceBranchName)_$(Build.Reason)

trigger:
  branches:
   include:
     - main
  paths:
   exclude:
     - azure-pipelines.yml

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

stages:
  - stage: Sync2GitHub
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
    - job: Sync
      displayName: Sync to Github
      pool:
        vmImage: ubuntu-20.04
      steps:
      - checkout: self
      - task: CmdLine@2
        displayName: Sync
        inputs:
          script: |
            git config user.email "smartide@leansoftx.com"
            git config user.name "smartide team"
            git pull https://github.com/SmartIDE/SmartIDE.git --no-rebase 
            git push https://$(github_pat)@github.com/SmartIDE/SmartIDE.git refs/remotes/origin/main:refs/heads/main

