kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: smartide-file-storageclass
provisioner: k8s.io/minikube-hostpath
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS