kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: smartide-file-storageclass-db
# provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
# allowVolumeExpansion: true
# mountOptions:
#   - dir_mode=0700
#   - file_mode=0700
#   - uid=999
#   - gid=999
#   - mfsymlinks
#   - cache=strict
#   - actimeo=30

provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db_remote"
  priority_io: "high"
  fs: "xfs"

